{
 "title": "COVID-19 Ukraine",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Stats - Timeseries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "Ukraine:confirmed", "type": "timeseries" },
    { "target": "Ukraine:deaths", "type": "timeseries" },
    { "target": "Ukraine:recovered", "type": "timeseries" }
   ]
  },
  {
   "title": "Total Confirmed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "targets": [
    { "target": "Ukraine:TotalCases", "type": "timeseries" }
   ]
  },
  {
   "title": "Active Cases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "targets": [
    { "target": "Ukraine:ActiveCases", "type": "timeseries" }
   ]
  },
  {
   "title": "Total Deaths",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "targets": [
    { "target": "Ukraine:TotalDeaths", "type": "timeseries" }
   ]
  },
  {
   "title": "Total Tests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "targets": [
    { "target": "Ukraine:TotalTests", "type": "timeseries" }
   ]
  },
  {
   "title": "Total Recovered",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "targets": [
    { "target": "Ukraine:TotalRecovered", "type": "timeseries" }
   ]
  },
  {
   "title": "Tests Per 1M Population",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "targets": [
    { "target": "Ukraine:Tests_1M_Pop", "type": "timeseries" }
   ]
  }
 ]
}